import path from "node:path";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

/** Generated by `drizzle-kit generate`; see drizzle.config.ts. */
const MIGRATIONS_FOLDER = path.join(process.cwd(), "drizzle");

/** Drops server notices such as "schema already exists, skipping" on reruns. */
function ignoreNotice(): void {}

/**
 * Applies the migrations in drizzle/ that the database has not seen yet, then
 * closes the connection. Running it again is a no-op.
 */
export async function runMigrations(url: string): Promise<void> {
  // `prepare: false` keeps this usable through the Supabase transaction pooler.
  const client = postgres(url, { max: 1, prepare: false, onnotice: ignoreNotice });
  try {
    await migrate(drizzle(client), { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await client.end();
  }
}
